### ISSUE TITLE
Adding a model to the parent collection is not firing an 'add' event in the subcollection

### ISSUE THREAD

**Issue by d3chapma** [anthonyshort/backbone.collectionsubset#9]
I'm using backbone v1.0 is that an issue?

**Comment by nickfun** [comment]
I've used collectionsubset with Backbone v1 and it works for me.

Is the model already in the parent collection and you are adding a model with newer data? it wont send an 'add' in that situation.

**Comment by d3chapma** [comment]
Found out it was a bug on my part. When I was setting the filter on the subcollection, the model hadn't finished syncing with the server, so it didn't have an id, which I was using in the filter. So I was making a filter based on a null value which of course never had any models get added to it.
